#index:
#    path: /
#    controller: App\Controller\DefaultController::index
auth_register:
  path: /auth/register
  controller: App\Controller\AuthController::register
  methods: POST

auth_login:
  path: /auth/login
  controller: App\Controller\AuthController::getTokenUser
